- hosts: database
  become: root
  vars:
    mysql_user_name: root
    mysql_password: root

  tasks:
  - name: Create website database
    mysql_db: 
      name=world
      login_user={{ mysql_user_name }}
      login_password={{ mysql_password }}
      state=present

  - name: Copy website database
    copy: 
      src=world.sql
      dest=/tmp/world.sql

  - name: Import website database
    mysql_db: 
      name=world
      login_user={{ mysql_user_name }}
      login_password={{ mysql_password }}
      target=/tmp/world.sql
      state=import
