# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: files/world.sql
    dest: /tmp

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/world.sql
