tasks:
  - name: Create website database
    mysql_db: 
      name=world
      login_user= {{ mysql_root_username }}
      login_password= {{ mysql_root_password }}
      state=present

  - name: Copy website database
    copy: 
      src=world.sql
      dest=/tmp/world.sql

  - name: Import website database
    mysql_db: 
      name=world
      login_user={{ mysql_root_username }}
      login_password= {{ mysql_root_password }}
      target=/tmp/world.sql
      state=import
